name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    ~ cron: '0 9,15,17 * * 1,2,3,4,5'

jobs:
  unity-tests:
    runs-on: ubuntu-latest
    
    steps:
      name: Checkout projeto
      users: actions/checkout@v2

      name: Setup node
      users: actions/setup-node@v2.2.0
      with: 
        node-version: ${{matrix.node-version}}

      name: Instal dependencies
      run: npm install

      name: Run Tests
      run: npm run test